# Generated by Django 4.2 on 2026-02-26 15:48

from django.db import migrations, models
import voteapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('voter_id', models.CharField(help_text='Unique Voter ID or Institutional ID', max_length=50, unique=True)),
                ('id_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('COLLEGE', 'College ID Card'), ('PAN', 'PAN Card'), ('VOTER', 'Government-issued Voter ID')], max_length=20)),
                ('id_proof_number', models.CharField(help_text='ID Proof Number (must be unique)', max_length=50, unique=True)),
                ('id_proof_image', models.ImageField(upload_to='id_proofs/', validators=[voteapp.models.validate_image_format])),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('face_image', models.ImageField(upload_to='faces/', validators=[voteapp.models.validate_image_format])),
                ('voted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
