# Generated by Django 4.2 on 2026-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='face_detected',
            field=models.BooleanField(default=False, help_text='Whether a valid face was detected'),
        ),
        migrations.AddField(
            model_name='voter',
            name='face_detection_confidence',
            field=models.FloatField(default=0.0, help_text='Face detection confidence score'),
        ),
        migrations.AddField(
            model_name='voter',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='Facial feature encoding data', null=True),
        ),
    ]
