# Generated by Django 4.2 on 2026-02-26 17:10

from django.db import migrations, models
import django.db.models.deletion
import voteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_voter_face_detected_voter_face_detection_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one election can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., President, Secretary, Treasurer', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('max_votes', models.IntegerField(default=1, help_text='Maximum votes a voter can cast for this position')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='voteapp.election')),
            ],
            options={
                'ordering': ['election', 'order', 'title'],
                'unique_together': {('election', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/', validators=[voteapp.models.validate_image_format])),
                ('bio', models.TextField(blank=True, help_text='Candidate biography/manifesto')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voteapp.position')),
            ],
            options={
                'ordering': ['position', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voteapp.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voteapp.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_votes', to='voteapp.voter')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('voter', 'candidate')},
            },
        ),
    ]
