# Generated by Django 4.2 on 2026-02-26 17:20

from django.db import migrations, models
import voteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_election_position_candidate_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, help_text='Political party or group (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(blank=True, help_text='Candidate election symbol', null=True, upload_to='candidate_symbols/', validators=[voteapp.models.validate_image_format]),
        ),
    ]
